public class Main8 {
     public static void main(String[] args) {
        String firstName;            //名前
        String famillyName;          //苗字
        String hometown;             //出身地
        String favoriteFood;         //好きな食べ物

        /**プロフィール作成 */

        firstName ="寧々";
        famillyName ="鬼塚"; 
        hometown ="福岡県";
        favoriteFood ="オムライス";

        System.out.println("=====自己紹介=====");
        System.out.println("名前："+famillyName +firstName \n"出身地："+hometown \n"好きな食べ物："+favoriteFood);
    }
}