public class Main7 {
    public static void main(String[] args) {
        // 名前、名字、年齢、メールアドレスの4つの変数を使用してください。
        String firstName;
        String famillyName;
        int age;
        String mailAddress;
        
        firstName ="太郎";
        famillyName ="山田";
        age =16;
        mailAddress = "yamada@example.com"

        System.out.println("名前："+famillyName +firstName);
        System.out.println("年齢："+age);
        System.out.println("メールアドレス："+mailAddress);

    }
}